# Generated by Django 4.1.7 on 2023-04-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_perfil_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('online', 'Online'), ('fisica', 'Fisica')], max_length=15)),
                ('lugar', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('juego_rol', models.CharField(max_length=150)),
                ('nombre_campanya', models.CharField(max_length=150)),
                ('num_partida', models.PositiveIntegerField(blank=True, default=0)),
                ('nivel_jugador', models.CharField(choices=[('iniciado', 'Iniciado'), ('casual', 'Casual'), ('experto', 'Experto')], max_length=15)),
                ('requisitos_jugador', models.CharField(blank=True, max_length=1000)),
                ('observaciones', models.CharField(blank=True, max_length=1000)),
                ('max_usuarios', models.PositiveIntegerField()),
                ('num_usuarios', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campanya/')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('online', 'Online'), ('fisica', 'Fisica')], max_length=15)),
                ('lugar', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nombre_juego', models.CharField(max_length=150)),
                ('nivel_jugador', models.CharField(choices=[('iniciado', 'Iniciado'), ('casual', 'Casual'), ('experto', 'Experto')], max_length=15)),
                ('requisitos_jugador', models.CharField(blank=True, max_length=1000)),
                ('observaciones', models.CharField(blank=True, max_length=1000)),
                ('max_usuarios', models.PositiveIntegerField()),
                ('num_usuarios', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partida/')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, choices=[('iniciado', 'Iniciado'), ('casual', 'Casual'), ('experto', 'Experto')], max_length=15)),
                ('experiencia_previa', models.CharField(blank=True, max_length=500)),
                ('observaciones', models.CharField(blank=True, max_length=2000)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugadores_jugador', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partida')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='jugadores',
            field=models.ManyToManyField(related_name='partidas_jugadores', through='api.PartidaJugador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampanyaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, choices=[('iniciado', 'Iniciado'), ('casual', 'Casual'), ('experto', 'Experto')], max_length=15)),
                ('experiencia_previa', models.CharField(blank=True, max_length=500)),
                ('nombre_personaje', models.CharField(blank=True, max_length=50)),
                ('clase_personaje', models.CharField(blank=True, max_length=100)),
                ('raza_personaje', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=2000)),
                ('campanya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campanya')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_campanyas_jugador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campanya',
            name='jugadores',
            field=models.ManyToManyField(related_name='partidas_campanyas', through='api.CampanyaJugador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campanya',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
