# Generated by Django 4.1.7 on 2023-04-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanya',
            name='provincia',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='api.provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='provincia',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='api.provincia'),
            preserve_default=False,
        ),
    ]
