# Generated by Django 4.1.7 on 2023-04-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_campanya_provincia_alter_partida_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanya',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provincia'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provincia'),
        ),
    ]
