# Generated by Django 4.1.7 on 2023-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_campanya_provincia_alter_partida_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanya',
            name='horas',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='horas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
