# Generated by Django 4.1.7 on 2023-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_campanya_horas_partida_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanya',
            name='horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
