# Generated by Django 4.1.7 on 2023-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_campanya_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
