# Generated by Django 4.1.7 on 2023-05-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_partida_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='horas',
        ),
    ]
