# Generated by Django 4.1.7 on 2023-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_partida_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
