# Generated by Django 4.1.7 on 2023-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_campanya_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanya',
            name='resumen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='resumen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
