# Generated by Django 4.1.7 on 2023-05-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_solicitudespartidas_solicitudescampanyas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudescampanyas',
            old_name='master',
            new_name='jugador_solicitante',
        ),
        migrations.RenameField(
            model_name='solicitudespartidas',
            old_name='master',
            new_name='jugador_solicitante',
        ),
    ]
