# Generated by Django 4.1.7 on 2023-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_master_solicitudescampanyas_jugador_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='proximas_partidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='proximas_terminadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
