# Generated by Django 4.1.7 on 2023-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_perfil_proximas_partidas_perfil_proximas_terminadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='proximas_partidas',
            new_name='juegos_terminados',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='proximas_terminadas',
        ),
        migrations.AddField(
            model_name='perfil',
            name='proximos_juegos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
